config/routes.rb
Precomp2011::Application.routes.draw do

  resources :presentations do
     resources :presentation_questions
  end

  resources :users

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/sessions/destroy', :to => 'sessions#destroy'
  match '/sessions/create', :to => 'sessions#create_by_name' if Rails.env.development?
  root :to => "presentations#index"
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :presentations
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :subject, :polymorphic => true
  belongs_to :user
  
  validates_presence_of :body, :user_id, :subject_id, :subject_type
  
  default_scope :order => 'created_at DESC'
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :presentations
  belongs_to :user

  validates_uniqueness_of :name
  validates_presence_of :name
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :starts_at
  validates_presence_of :speaker_name
  
  has_many :presentation_questions
end

app/models/presenter_profile.rb
class PresenterProfile < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :presentations
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user # making the rating
  belongs_to :presentation

  validates_uniqueness_of :user_id, :scope => :presentation_id
end

app/models/session.rb
class Session < ActiveRecord::Base
  has_and_belongs_to_many :presenters, :class_name => 'User'
  belongs_to :category
  has_many :comments
  has_many :ratings
  validates_presence_of :title, :start_time, :location
  
  def positive_ratings
    ratings.select{|r| r.score == 1}
  end
  
  def negative_ratings
    ratings.select{|r| r.score == -1}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :presentation_questions
  has_and_belongs_to_many :achievements
  
  def self.create_from_hash!(hash)
    create(:name => hash['user_info']['name'])
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  def index
    @presentations = Presentation.find(:all, :order => "name")
  end
  
  def new
    @presentation = Presentation.new
  end

  def create
    @presentation = Presentation.new(params[:presentation])
    if(@presentation.save)
      flash[:success] = "Presentation '#{@presentation.name}' created!"
      redirect_to presentation_path(@presentation)
    else 
      flash[:error] = "FAIL!<br>#{@presentation.errors.full_messages.join("<br>")}"
      render :new
    end
  end

  def show
    @presentation = Presentation.find(params[:id])
  end

  def edit
    @presentation = Presentation.find(params[:id])
  end

  def update
    @presentation = Presentation.find(params[:id])
    if @presentation.update_attributes(params[:presentation])
      flash[:success] = "Presentation '#{@presentation.name}' updated!"
      redirect_to presentation_path(@presentation)
    else
      flash[:error] = "FAIL!<br>#{@presentation.errors.full_messages.join("<br>")}"
      render :edit
    end
  end

  def destroy 
    @presentation = Presentation.find(params[:id])
    @presentation.destroy
    flash[:success] = "Presentation #{@presentation.name} has been removed with extreme prejudice"
    redirect_to presentations_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_authorization

	def show
	  @user = User.find(params[:id])
	end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/helpers/presenters_helper.rb
module PresentersHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/presentations/_form.html.erb
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
    </p>

  <p>
    <%= form.label :starts_at %>
    <%= form.datetime_select :starts_at %>
    </p>
  <p>
    <%= form.label :speaker_name %>
    <%= form.text_field :speaker_name %>
    </p>

app/views/presentations/_presentation.html.erb
<div class="presentation">
  <%= render :partial => "vote_count", :locals => { :presentation => presentation, :can_vote => @user_ratings.find{|u| u.presentation == presentation}.nil?} %>
  <h3><%= presentation.title %> ( <%= if presentation.category.nil? then "Unknown" else presentation.category.title end %> )</h3>
  <p><%= presentation.start_time %> @ <%= presentation.location %></p>
  <p><strong>Technology/Platform:</strong> <%= presentation.technology %></p>
  <p><strong>Difficulty Level:</strong> <%= presentation.level %></p>
  <p><strong>Abstract:</strong> <%= presentation.description %></p>
  <%= render :partial => "comments/comments", :locals => {:comments => presentation.comments, :subject => presentation }%>
</div>

app/views/presentations/_presentation_co.html.erb
<div class="presentation">
  <%= render :partial => "vote_count", :locals => { :presentation => presentation_co, :can_vote => @user_ratings.find{|u| u.presentation == presentation_co}.nil?} %>
  <h3><%= presentation_co.title %> ( <%= if presentation_co.category.nil? then "Unknown" else presentation_co.category.title end %> )</h3>
  <p><%= presentation_co.start_time %> @ <%= presentation_co.location %></p>
  <p><strong>Technology/Platform:</strong> <%= presentation_co.technology %></p>
  <p><strong>Difficulty Level:</strong> <%= presentation_co.level %></p>
  <p><strong>Abstract:</strong> <%= presentation_co.description %></p>
  <%= link_to "Edit", :action => 'edit', :id => presentation_co %>
  <%= link_to "Delete", :action => 'delete', :id => presentation_co %>
  <%= render :partial => "comments/comments", :locals => {:comments => presentation_co.comments, :subject => presentation_co }%>
</div>

app/views/presentations/_vote_count.html.erb
<div class="vote_count">
  <span class="thumbs_up"><%= presentation.positive_ratings %></span>
  <% if can_vote then %>
    <%= link_to image_tag("thumbs_up.png"), :action => :vote_up, :id => presentation %>
  <% else %>
    <%= image_tag("thumbs_up.png") %>
  <% end %>
  &nbsp;
  <span class="thumbs_down"><%= presentation.negative_ratings %></span>
  <% if can_vote then %>
    <%= link_to image_tag("thumbs_down.png"), :action => :vote_down, :id => presentation %>
  <% else %>
    <%= image_tag("thumbs_down.png") %>
  <% end %>
</div>

app/views/presentations/create.html.erb
<h1>Presentation#create</h1>
<p>Find me in app/views/presentation/create.html.erb</p>

app/views/presentations/destroy.html.erb
<h1>Presentation#destroy</h1>
<p>Find me in app/views/presentation/destroy.html.erb</p>

app/views/presentations/edit.html.erb
<p><%= flash[:error] if flash[:error] %></p>
<%= form_for(@presentation) do |form| %>
  <%= render "form", :form => form %>
  <p>
  <%= form.submit "Edit Presentation" %>
  </p>
<% end %>

app/views/presentations/index.html.erb
<%= link_to "all presentations", presentations_path %>
<div>
  Filter: <input type="text" id='FilterPresentationTextbox' /> &nbsp; &nbsp; 
  Sort: <select id="PresentationSort">
          <option value="data-title">Title</option>
          <option value="data-start">Start Date</option>
          <option value="data-presenter">Presenter</option>
        </select>
</div>

<div class='presentation_list'>
  <ul>
    <% @presentations.each do |presentation| %>
      <li data-title='<%= presentation.name %>'
          data-start='<%= presentation.starts_at.to_s(:long) %>'
          data-presenter='<%= presentation.speaker_name%>'>
        <div class='presentation'>
            <%= link_to presentation.name, presentation %><br/>
            Start: <%= presentation.starts_at.to_s(:long) %><br/>
            Presenter: <%= presentation.speaker_name %>
          </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/presentations/new.html.erb
<p><%= flash[:error] if flash[:error] %></p>
<%= form_for(@presentation) do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
    </p>

  <p>
    <%= form.label :starts_at %>
    <%= form.datetime_select :starts_at %>
    </p>
  <p>
    <%= form.label :speaker_name %>
    <%= form.text_field :speaker_name %>
    </p>
  <p>
  <%= form.submit "Create Presentation" %>
  </p>
<% end %>

app/views/presentations/show.html.erb
<p><%= flash[:success] if flash[:success] %></p>
<h2>Presentation: <%= @presentation.name %></h2>
<p>
  <%= link_to 'Edit', edit_presentation_path(@presentation)  %>
  <%= link_to 'Kill It', presentation_path(@presentation), :confirm => "really??", :method => :delete  %>
</p>

<h3>Questions:</h3>
<ul id="questions">
  <%= render @presentation.presentation_questions %>
</ul>


<%= link_to "Ask a question", new_presentation_presentation_question_path(@presentation), :id => 'question_link' %>

<%= render 'presentation_questions/form' %>

app/views/presentations/update.html.erb
<h1>Presentation#update</h1>
<p>Find me in app/views/presentation/update.html.erb</p>